version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SICAE_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SICAE_DATABASE_PASSWORD}
      POSTGRES_DB: ${SICAE_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /rails
    env_file:
      - .env
    environment:
      SICAE_DATABASE_HOST: db
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0 -p 3000

volumes:
  db_data:
  bundle_cache: