require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/escolas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Escola. As you add validations to Escola, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Escola.create! valid_attributes
      get escolas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      escola = Escola.create! valid_attributes
      get escola_url(escola)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_escola_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      escola = Escola.create! valid_attributes
      get edit_escola_url(escola)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Escola" do
        expect {
          post escolas_url, params: { escola: valid_attributes }
        }.to change(Escola, :count).by(1)
      end

      it "redirects to the created escola" do
        post escolas_url, params: { escola: valid_attributes }
        expect(response).to redirect_to(escola_url(Escola.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Escola" do
        expect {
          post escolas_url, params: { escola: invalid_attributes }
        }.to change(Escola, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post escolas_url, params: { escola: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested escola" do
        escola = Escola.create! valid_attributes
        patch escola_url(escola), params: { escola: new_attributes }
        escola.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the escola" do
        escola = Escola.create! valid_attributes
        patch escola_url(escola), params: { escola: new_attributes }
        escola.reload
        expect(response).to redirect_to(escola_url(escola))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        escola = Escola.create! valid_attributes
        patch escola_url(escola), params: { escola: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested escola" do
      escola = Escola.create! valid_attributes
      expect {
        delete escola_url(escola)
      }.to change(Escola, :count).by(-1)
    end

    it "redirects to the escolas list" do
      escola = Escola.create! valid_attributes
      delete escola_url(escola)
      expect(response).to redirect_to(escolas_url)
    end
  end
end
