require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/item_precos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ItemPreco. As you add validations to ItemPreco, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ItemPreco.create! valid_attributes
      get item_precos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      item_preco = ItemPreco.create! valid_attributes
      get item_preco_url(item_preco)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_item_preco_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      item_preco = ItemPreco.create! valid_attributes
      get edit_item_preco_url(item_preco)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ItemPreco" do
        expect {
          post item_precos_url, params: { item_preco: valid_attributes }
        }.to change(ItemPreco, :count).by(1)
      end

      it "redirects to the created item_preco" do
        post item_precos_url, params: { item_preco: valid_attributes }
        expect(response).to redirect_to(item_preco_url(ItemPreco.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ItemPreco" do
        expect {
          post item_precos_url, params: { item_preco: invalid_attributes }
        }.to change(ItemPreco, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post item_precos_url, params: { item_preco: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested item_preco" do
        item_preco = ItemPreco.create! valid_attributes
        patch item_preco_url(item_preco), params: { item_preco: new_attributes }
        item_preco.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the item_preco" do
        item_preco = ItemPreco.create! valid_attributes
        patch item_preco_url(item_preco), params: { item_preco: new_attributes }
        item_preco.reload
        expect(response).to redirect_to(item_preco_url(item_preco))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        item_preco = ItemPreco.create! valid_attributes
        patch item_preco_url(item_preco), params: { item_preco: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested item_preco" do
      item_preco = ItemPreco.create! valid_attributes
      expect {
        delete item_preco_url(item_preco)
      }.to change(ItemPreco, :count).by(-1)
    end

    it "redirects to the item_precos list" do
      item_preco = ItemPreco.create! valid_attributes
      delete item_preco_url(item_preco)
      expect(response).to redirect_to(item_precos_url)
    end
  end
end
