require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tabela_precos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TabelaPreco. As you add validations to TabelaPreco, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TabelaPreco.create! valid_attributes
      get tabela_precos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tabela_preco = TabelaPreco.create! valid_attributes
      get tabela_preco_url(tabela_preco)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tabela_preco_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tabela_preco = TabelaPreco.create! valid_attributes
      get edit_tabela_preco_url(tabela_preco)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TabelaPreco" do
        expect {
          post tabela_precos_url, params: { tabela_preco: valid_attributes }
        }.to change(TabelaPreco, :count).by(1)
      end

      it "redirects to the created tabela_preco" do
        post tabela_precos_url, params: { tabela_preco: valid_attributes }
        expect(response).to redirect_to(tabela_preco_url(TabelaPreco.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TabelaPreco" do
        expect {
          post tabela_precos_url, params: { tabela_preco: invalid_attributes }
        }.to change(TabelaPreco, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tabela_precos_url, params: { tabela_preco: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tabela_preco" do
        tabela_preco = TabelaPreco.create! valid_attributes
        patch tabela_preco_url(tabela_preco), params: { tabela_preco: new_attributes }
        tabela_preco.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tabela_preco" do
        tabela_preco = TabelaPreco.create! valid_attributes
        patch tabela_preco_url(tabela_preco), params: { tabela_preco: new_attributes }
        tabela_preco.reload
        expect(response).to redirect_to(tabela_preco_url(tabela_preco))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tabela_preco = TabelaPreco.create! valid_attributes
        patch tabela_preco_url(tabela_preco), params: { tabela_preco: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tabela_preco" do
      tabela_preco = TabelaPreco.create! valid_attributes
      expect {
        delete tabela_preco_url(tabela_preco)
      }.to change(TabelaPreco, :count).by(-1)
    end

    it "redirects to the tabela_precos list" do
      tabela_preco = TabelaPreco.create! valid_attributes
      delete tabela_preco_url(tabela_preco)
      expect(response).to redirect_to(tabela_precos_url)
    end
  end
end
