default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV.fetch("SICAE_DATABASE_NAME") { "sicae_development" } %>

  username: <%= ENV["SICAE_DATABASE_USERNAME"] || ENV["DB_USERNAME"] %>
  password: <%= ENV["SICAE_DATABASE_PASSWORD"] || ENV["DB_PASSWORD"] %>
  host: <%= ENV["SICAE_DATABASE_HOST"] || ENV["DB_HOST"] %>
  port: <%= ENV["SICAE_DATABASE_PORT"] || ENV["DB_PORT"] %>


test:
  <<: *default
  database: <%= ENV.fetch("SICAE_DATABASE_NAME") { "sicae_test" } %>
  username: <%= ENV["SICAE_DATABASE_USERNAME"] || ENV["DB_USERNAME"] %>
  password: <%= ENV["SICAE_DATABASE_PASSWORD"] || ENV["DB_PASSWORD"] %>
  host: <%= ENV["SICAE_DATABASE_HOST"] || ENV["DB_HOST"] %>
  port: <%= ENV["SICAE_DATABASE_PORT"] || ENV["DB_PORT"] %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("SICAE_DATABASE_NAME") { "sicae_production" } %>
    username: <%= ENV["SICAE_DATABASE_USERNAME"] || ENV["DB_USERNAME"] || "sicae" %>
    password: <%= ENV["SICAE_DATABASE_PASSWORD"] || ENV["DB_PASSWORD"] %>
    host: <%= ENV["SICAE_DATABASE_HOST"] || ENV["DB_HOST"] %>
    port: <%= ENV["SICAE_DATABASE_PORT"] || ENV["DB_PORT"] %>
  cache:
    <<: *primary_production
    database: sicae_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sicae_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sicae_production_cable
    migrations_paths: db/cable_migrate
