# Name of your application. Used to uniquely configure containers.
service: sicae

# Name of the container image (use your-user/app-name on external registries).
image: sicae

# Deploy to these servers.
servers:
  web:
    - 167.99.9.36

# Using DigitalOcean Container Registry
registry:
  server: registry.digitalocean.com
  username: sicae
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: sicae-db
    DB_USERNAME: sicae
    DB_NAME: sicae_production
    SICAE_DATABASE_HOST: sicae-db
    SICAE_DATABASE_USERNAME: sicae
    SICAE_DATABASE_NAME: sicae_production

# Aliases
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for Active Storage
volumes:
  - "sicae_storage:/rails/storage"

# Bridge fingerprinted assets
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
  secrets:
    - RAILS_MASTER_KEY

# Use a different ssh user than root
ssh:
  user: root

# Use accessory services
accessories:
  db:
    image: postgres:16
    host: 167.99.9.36
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: sicae
        POSTGRES_DB: sicae_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    options:
      volume_driver: local
